### ISSUE TITLE
read-only error on Snap installation

### ISSUE THREAD

**Issue by jhmk** [malko/rocketchat-jira-hook#1]
When installing Rocket.Chat via Snap it creating a read-only snap dir.
If I now try to add this Webhook the following messages appear:

> EROFS: read-only file system, mkdir '/snap/rocketchat-server/74/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/.babel-cache'

The problem depends most on a not separate dir for Cache & Temp files which is write-able.

Any way to set a different .babel-cache URL in the Script?

**Comment by malko** [comment]
This is not related to this script you should report to the rocket chat project instead or to the snap package maintainer
