### ISSUE TITLE
Just to communicate possible improvements made

### ISSUE THREAD

**Issue by rjmfernandes** [malko/rocketchat-jira-hook#10]
Hi, I have incorporated some changes on your script. They are available here: https://github.com/rjmfernandes/rocketchat-jira-hook In case you want to merge that with yours.

**Comment by malko** [comment]
Thanks will have a look tomorrow

**Comment by malko** [comment]
You can propose a PR if you want, I'm wondering why you changed 
line 59 from
if ( **!** change.field.match('status|resolution|comment|priority')) {
to 
if (change.field.match('status|resolution|comment|priority')) {

**Comment by rjmfernandes** [comment]
will review and let you know, this change might have slipped through while testing

**Comment by malko** [comment]
Ok waiting your reply before applying your changes

**Comment by rjmfernandes** [comment]
Hi, that got in by distraction cause I wanted to process description updates and that if condition was blocking. I should just have removed it completely which is what I just did. Now I dont have that if statement and all updates are processed.

**Comment by malko** [comment]
Merged thanks for your contrib
