### ISSUE TITLE
Jira attachment or issue linking actions ignored by rocket.chat

### ISSUE THREAD

**Issue by bumperboy** [malko/rocketchat-jira-hook#13]
We have configured several Jira Cloud - Rocket.Chat Webhooks using this guide: https://docs.rocket.chat/use-rocket.chat/workspace-administration/integrations/jira

and your script: https://github.com/malko/rocketchat-jira-hook/blob/master/jira-rocketchat-hook.js

The majority of the webhooks are working successfully except the ones that should "notify" regarding the addition/removal of attachments or addition/removal of links.

As you can see from the Rocket.Chat logs, all the mentioned events are ignored by Rocket.Chat and no notification is displayed in the Rocket.Chat channel.

Jira event attachment_deleted. Not enough info on issue. Event ignored. 
Jira event attachment_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event attachment_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Not enough info on issue. Event ignored. 
Jira event attachment_created. Not enough info on issue. Event ignored. 
Jira event attachment_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 
Jira event issuelink_deleted. Not enough info on issue. Event ignored. 

Could you please help us with this?

Thank you

**Comment by malko** [comment]
Hi,

Can you please set PRINT_PAYLOAD_IF_IGNORED to true and copy paste rocketchat related logs to such events. It should contain the payload of the event and will greatly help on understanding the problem.

**Comment by malko** [comment]
Also probably the issue field is not filled when receiving the event or there is no user.name set.

**Comment by bumperboy** [comment]
![image](https://github.com/malko/rocketchat-jira-hook/assets/2044970/be772a25-2ffb-4dec-b2cd-ae45b01b4709)

Changed the settings as requested and this is the info in the logs (domain masked)

Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event attachment_deleted. Not enough info on issue. Event ignored. 
{   "timestamp": 1686846762666,   "webhookEvent": "attachment_deleted",   "attachment": {     "self": "https://myinstance.atlassian.net/rest/api/2/attachment/16793",     "id": "16793",     "filename": "This is a test.txt",     "author": {       "self": "https://myinstance.atlassian.net/rest/api/2/user?accountId=627ce05681d82e00680c546b",       "accountId": "627ce05681d82e00680c546b",       "avatarUrls": {         "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/M-6.png",         "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/M-6.png",         "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/M-6.png",         "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/M-6.png"       },       "displayName": "USER_012",       "active": true,       "timeZone": "Europe/Paris",       "accountType": "atlassian"     },     "created": "2023-06-15T09:27:15.244+0200",     "size": 14,     "mimeType": "text/plain",     "content": "https://myinstance.atlassian.net/rest/api/2/attachment/content/16793"   } } 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
{   "timestamp": 1686846771185,   "webhookEvent": "issuelink_created",   "issueLink": {     "id": 12290,     "sourceIssueId": 13373,     "destinationIssueId": 13316,     "issueLinkType": {       "id": 10000,       "name": "Blocks",       "outwardName": "blocks",       "inwardName": "is blocked by",       "isSubTaskLinkType": false,       "isSystemLinkType": false     },     "systemLink": false   } } 
Jira event issuelink_created. Not enough info on issue. Event ignored. 
Jira event attachment_created. Not enough info on issue. Event ignored.



Thank you for your help.

**Comment by malko** [comment]
Ok so as guessed there's no info related to the jira issue. 
What message would you expect to be displayed for such events with the information provided in the payload ?

**Comment by malko** [comment]
@bumperboy ?

**Comment by bumperboy** [comment]
Basically, it should display a standard rocket.chat notification with the name of the user that did the action and the name of the attachment. I don't understand is why the attachment details are displayed when a user attached a file and provided a comment but nothing is displayed if no comment is provided

**Comment by bumperboy** [comment]
![example](https://github.com/malko/rocketchat-jira-hook/assets/2044970/e1143744-faab-43a2-8c17-cbfd481730da)
Here is an example of the notification received when a comment is added to a ticket and that comment contains an attachment and a link

**Comment by malko** [comment]
Regarding the attachment problem, I think the problem is more related to why the call to the webhook doesn't embed information about the issue this can't be resolved at this repository level. You should probably report it to atlassian.

Regarding the link issue the problem is a little bit different, we have ids for related issues, but we still miss some information. A message with the relation and issue Id can be added but it would require rocketChat to call the api to gather meaningful information about those issue to make a valuable message with at least issues titles. 

Finally I guess it works when there's comments because it trigger a "comment_created" event which is correctly handle by the script.

In the current state of things I don't see what to do at this project level, do you have any suggestions ?

**Comment by bumperboy** [comment]
Dear Malko,
Thank you for your feedback.
I will check with Atlassian for the attachment problem.
