### ISSUE TITLE
Add a licence for this repository

### ISSUE THREAD

**Issue by kiwi-oss** [malko/rocketchat-jira-hook#14]
I would like to request adding a licence to this repository to make it legally safe to use it and clarify what is allowed and what isn't.

Without a licence, the copyright laws apply which means no one is allowed to copy or modify the script without explicit permission. Not being allowed to copy this particular script defies its purpose since it's meant to be copied into the Rocket Chat settings.

**Comment by malko** [comment]
Will do that when I have 5 minutes to do it, in the meanwhile, i can already tell you that it will be an MIT licence so you can start to use it right now accordingly ;)

**Comment by malko** [comment]
done

**Comment by kiwi-oss** [comment]
Great, thanks a lot! :heart:
