### ISSUE TITLE
couldn't make it work

### ISSUE THREAD

**Issue by MosabWadea** [malko/rocketchat-jira-hook#4]
Hi 
I am trying to make this webhook method to work with my chat and unfortunately I wasn't able to.

I have followed all the steps right and still nothing works. Can someone please tell me how to debug ?

I am trying to locate the problem source first, is it from jira or rocketchat, can someone give me an example outgoing header from jira to inject it using curl?

**Comment by MosabWadea** [comment]
@malko

**Comment by malko** [comment]
This repo wasn't maintained since long time, hope you found a solution. I close this as it is too old now and is not related to a bug in the code
