### ISSUE TITLE
Timestamp of Attachment ist not set

### ISSUE THREAD

**Issue by mcsage** [malko/rocketchat-jira-hook#6]
This seems to be the same problem we see with the gitlab hook js script.

https://github.com/malko/rocketchat-gitlab-hook/issues/23

**Comment by malko** [comment]
Yes for sure, but our jira integration doesn't work anymore at work as it is on a separate network. Can you propose a PR and test it on your side if you have a working integration. I'll be glad to merge it :)

**Comment by Monolithys** [comment]
Hello! I can test it, but i did not good enough to integrate it by myself

**Comment by tmp27017** [comment]
timestamp of attachment is 'January 1, 1970 7:00 AM', how fix it ?

**Comment by Monolithys** [comment]
> timestamp of attachment is 'January 1, 1970 7:00 AM', how fix it ?

who knows...
i am sitting here for 2 weeks and nobody answer to preveusly question.
this error was fixed somehow in gitlab integration, but i can't understand how to use it in this script

My programers help me some:
![image](https://user-images.githubusercontent.com/32746979/53806310-aab4e100-3f5d-11e9-9957-c3ce354d4ab9.png)

It's not good enough, we take current time, but not take timestamp from webhook. But it is look better.

**Comment by jbahillo** [comment]
THis should be fixed with https://github.com/malko/rocketchat-jira-hook/pull/7

**Comment by malko** [comment]
this have been merged sorry for the really long delay
