### ISSUE TITLE
Option to send direct messages to @-mentioned users

### ISSUE THREAD

**Issue by chfischer** [malko/rocketchat-jira-hook#8]
According to [https://github.com/RocketChat/Rocket.Chat/issues/15057](this) the channel specified in the webhook integration in rocket chat is only the "default channel", and can be overwritten by the script.. great.

This means that we could notify users in rocketchat if they are mentioned in jira, in addition to posting the infos into the designated #channel.

A mentioned user looks like this in the body field of the json file: [~username]. 

How would the script has to be improved to do this?

**Comment by malko** [comment]
It's a long time I haven't use Jira nor RocketChat, but in my memory the hook can only be bound to specific channels. I've no time to investigate on this one, but any PR will be welcome

**Comment by malko** [comment]
closed for inactivity, you can reopen if needed

**Comment by sgohl** [comment]
@chfischer  did you ever find a solution? When I try to add `@all` to the actual message in the Jira Automation Rules textbox, Rocketchat does not translate it into a mention, instead just writes `@all` as text.
